### ISSUE TITLE
Add a golang implementation

### ISSUE THREAD

**Issue by brendandburns** [metaparticle-io/package#5]
It would be great to have a `go` implementation of Metaparticle/Package

**Comment by vbmade2000** [comment]
Can I work on this ?

**Comment by xfernando** [comment]
I got a preliminary golang implementation working. I based it on the java implementation and implemented the docker, azure and metaparticle backends, but I've only tested the docker backend so far.

Since go does not have annotations I used structs that are passed to the Containerize() wrapper to implement the equivalent behavior. Like below:

```go
func main() {
	metaparticle.Containerize(
		&metaparticle.Runtime{
			Ports:           []int32{port},
			Shards:          0,
			URLShardPattern: "^\\/users\\/([^\\/]*)\\/.*",
			Executor:        "docker"},
		&metaparticle.Package{Repository: "xfernando",
			Builder: "docker",
			Verbose: true},
		func() {
			log.Println("Starting server on :8080")
			http.HandleFunc("/", handler)
			err := http.ListenAndServe(fmt.Sprintf(":%d", port), nil)
			if err != nil {
				log.Fatal("Couldn't start the server: ", err)
			}
		})
}
```

I'm putting some finishing touches before I submit a PR.

**Comment by vbmade2000** [comment]
Cool @xfernando.

**Comment by xfernando** [comment]
PR #20 submitted.
