### ISSUE TITLE
Add support to docker registry authentication using docker API

### ISSUE THREAD

**Issue by xfernando** [metaparticle-io/package#72]
I saw that the use of docker's client API was reverted for pushing the images because of lack of authentication support.

Reading docker's client API I found that [auth.go](https://github.com/moby/moby/blob/947eb283dc86b67ea487ed3b7c02ede7b1fbbafd/api/types/auth.go#L4-L22) has the type AuthConfig which is used to set authentication options on API requests.

So I wanted to get an opinion before I start implementing it.

Adding either the token or the user/password to the metaparticle "annotation" is obviously a bad idea, we don't want anyone commiting secrets to the repositories.

So I was thinking that environment variables are the best (maybe only?) option, so I was thinking that we could define that some environment variables can be used for authenticating with the api, as such:

METAPARTICLE_REGISTRY_USER
METAPARTICLE_REGISTRY_PASSWORD
and
METAPARTICLE_REGISTRY_TOKEN

So, we could check if a token env variable is defined, and use it, otherwise fallback to the user/password env variables. And if none are defined just let it try without authentication and if it fails for auth reasons, suggest setting these variables.

What does everyone think?

**Comment by srini85** [comment]
@xfernando - Yeah I think environment variable sounds right from my POV. I did a similar thing with the image name for dotnet which @brendandburns burns merged 

Except my Env Variable prefix was just MP not METAPARTICLE :)
#71

**Comment by xfernando** [comment]
@srini85 Nice, but I think we should probably get a consensus on the environment variables names so they don't differ between languages! :)

**Comment by dekkagaijin** [comment]
It's also possible to perform the same credential resolution that the `docker` client does, if you desire a more seamless experience. Here's a concise breakdown of precedence for credential sources in python:
https://github.com/google/containerregistry/blob/master/client/docker_creds_.py#L222

Note that we only support Basic (username, password) client auth in this lib, since Bearer (registrytoken) isn't practically supported by other clients yet.
